# use this by doing this in terminal:
# make
# make run (or make compile, make clean etc.)
CPPflags = gcc  # -wall
#LIB =  -larmadillo
all: 
	${CPPflags} -o main.exe main.c src/read_graph_from_file.c -Wall


run:
	./main.exe

clean:
	rm -f *.exe *~

plot:



